	let
	    Source = Sql.Database("OSLWVSQL006P", "DWDataMart"),
	    dbo_IncidentDimvw = Source{[Schema="dbo",Item="IncidentDimvw"]}[Data],
	    #"Removed Other Columns" = Table.SelectColumns(dbo_IncidentDimvw,{"Classification", "CreatedDate", "DisplayName", "Id", "ResolvedDate", "Source", "Status", "TierQueue"}),
	    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"DisplayName", "CreatedDate", "ResolvedDate"}),
	    #"Removed Top Rows" = Table.Skip(#"Reordered Columns",1),
	    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Top Rows",{{"CreatedDate", type datetime}}),
	    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type1",{{"ResolvedDate", type datetime}}),
	    #"Changed Type3" = Table.TransformColumnTypes(#"Changed Type2",{{"DisplayName", type text}}),
	    #"Added Custom" = Table.AddColumn(#"Changed Type3", "Durration", each [ResolvedDate] - [CreatedDate]),
	    #"Merged Queries" = Table.NestedJoin(#"Added Custom",{"Classification"},IncidentClassificationvw,{"ID"},"NewColumn"),
	    #"Expanded NewColumn" = Table.ExpandTableColumn(#"Merged Queries", "NewColumn", {"IncidentClassificationValue"}, {"NewColumn.IncidentClassificationValue"}),
	    #"Remove Classification Column" = Table.RemoveColumns(#"Expanded NewColumn", "Classification"),
	    #"Calculated Total Hours" = Table.TransformColumns(#"Remove Classification Column",{{"Durration", Duration.TotalHours}}),
	    #"Duplicated Column" = Table.DuplicateColumn(#"Calculated Total Hours", "CreatedDate", "CreatedDate - Copy"),
	    #"Extracted Year" = Table.TransformColumns(#"Duplicated Column",{{"CreatedDate - Copy", Date.Year}}),
	    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Year",{{"CreatedDate - Copy", Int64.Type}}),
	    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"CreatedDate - Copy", "CreatedDateYear"}}),
	    #"Duplicated Column1" = Table.DuplicateColumn(#"Renamed Columns", "CreatedDate", "CreatedDate - Copy"),
	    #"Changed Type4" = Table.TransformColumnTypes(#"Duplicated Column1",{{"CreatedDate - Copy", type date}}),
	    #"Added Custom1" = Table.AddColumn(#"Changed Type4", "Month", each Date.Month( [#"CreatedDate - Copy"])),
	    #"Merged Queries1" = Table.NestedJoin(#"Added Custom1",{"Source"},IncidentSourcevw,{"ID"},"NewColumn"),
	    #"Expanded NewColumn1" = Table.ExpandTableColumn(#"Merged Queries1", "NewColumn", {"IncidentSourceValue"}, {"NewColumn.IncidentSourceValue"}),
	    #"Merged Queries2" = Table.NestedJoin(#"Expanded NewColumn1",{"Status"},IncidentStatusvw,{"ID"},"NewColumn"),
	    #"Expanded NewColumn2" = Table.ExpandTableColumn(#"Merged Queries2", "NewColumn", {"IncidentStatusValue"}, {"NewColumn.IncidentStatusValue"}),
	    #"Removed Columns" = Table.RemoveColumns(#"Expanded NewColumn2",{"Source", "Status"}),
	    #"Merged Queries3" = Table.NestedJoin(#"Removed Columns",{"TierQueue"},IncidentTierQueuesvw,{"ID"},"NewColumn"),
	    #"Expanded NewColumn3" = Table.ExpandTableColumn(#"Merged Queries3", "NewColumn", {"IncidentTierQueuesValue"}, {"NewColumn.IncidentTierQueuesValue"}),
	    #"Removed Columns1" = Table.RemoveColumns(#"Expanded NewColumn3",{"TierQueue"}),
	    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"NewColumn.IncidentTierQueuesValue", "Incident.SupportGroup"}, {"NewColumn.IncidentStatusValue", "Incident.Status"}, {"NewColumn.IncidentSourceValue", "Incident.Source"}, {"NewColumn.IncidentClassificationValue", "Incident.Classification"}, {"DisplayName", "Incident.Displayname"}, {"CreatedDate", "Incident.CreatedDate"}, {"ResolvedDate", "Incident.ResolvedDate"}, {"Durration", "Incident.CR.Durration"}, {"CreatedDateYear", "Incident.CR.Year"}, {"Month", "Incident.CR.Month"}}),
	    #"Cleaned Text" = Table.TransformColumns(Table.TransformColumnTypes(#"Renamed Columns1", {{"Incident.CR.Year", type text}}, "nb-NO"),{{"Incident.CR.Year", Text.Clean}}),
	    #"Removed Columns2" = Table.RemoveColumns(#"Cleaned Text",{"CreatedDate - Copy"}),
	    #"Duplicated Column2" = Table.DuplicateColumn(#"Removed Columns2", "Incident.ResolvedDate", "Incident.ResolvedDate - Copy"),
	    #"Renamed Columns2" = Table.RenameColumns(#"Duplicated Column2",{{"Incident.ResolvedDate - Copy", "Incident.RS.Resolved.Month"}}),
	    #"Extracted Month" = Table.TransformColumns(#"Renamed Columns2",{{"Incident.RS.Resolved.Month", Date.Month}}),
	    #"Inserted Year" = Table.AddColumn(#"Extracted Month", "Year", each Date.Year([Incident.ResolvedDate]), type number),
	    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Year",{{"Year", "Incident.Resolved.Year"}, {"Incident.RS.Resolved.Month", "Incident.Resolved.Month"}}),
	    #"Cleaned Text1" = Table.TransformColumns(Table.TransformColumnTypes(#"Renamed Columns3", {{"Incident.Resolved.Year", type text}, {"Incident.Resolved.Month", type text}}, "nb-NO"),{{"Incident.Resolved.Year", Text.Clean}, {"Incident.Resolved.Month", Text.Clean}}),
	    #"Changed Type5" = Table.TransformColumnTypes(#"Cleaned Text1",{{"Incident.Resolved.Month", Int64.Type}, {"Incident.Resolved.Year", Int64.Type}}),
	    #"Cleaned Text2" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type5", {{"Incident.CR.Month", type text}}, "nb-NO"),{{"Incident.CR.Year", Text.Clean}, {"Incident.CR.Month", Text.Clean}}),
	    #"Changed Type6" = Table.TransformColumnTypes(#"Cleaned Text2",{{"Incident.CR.Year", Int64.Type}, {"Incident.CR.Month", Int64.Type}}),
	    #"Cleaned Text3" = Table.TransformColumns(Table.TransformColumnTypes(#"Changed Type6", {{"Incident.CR.Year", type text}, {"Incident.CR.Month", type text}, {"Incident.Resolved.Month", type text}, {"Incident.Resolved.Year", type text}}, "nb-NO"),{{"Incident.CR.Year", Text.Clean}, {"Incident.CR.Month", Text.Clean}, {"Incident.Resolved.Month", Text.Clean}, {"Incident.Resolved.Year", Text.Clean}}),
	    #"Inserted Date" = Table.AddColumn(#"Cleaned Text3", "Date", each DateTime.Date([Incident.ResolvedDate]), type date),
	    #"Renamed Columns4" = Table.RenameColumns(#"Inserted Date",{{"Date", "Incident.Resolved.Date"}, {"Id", "Incident.ID"}}),
	    #"Inserted Date1" = Table.AddColumn(#"Renamed Columns4", "Date", each DateTime.Date([Incident.CreatedDate]), type date),
	    #"Renamed Columns5" = Table.RenameColumns(#"Inserted Date1",{{"Date", "Incident.CR.CreatedDate"}})
	in
	    #"Renamed Columns5"
